#include <SMAAspUserSubroutines.hdr>
C D2 tiny transferred-state ingestion UEL/UMAT.
C Separate D2-only source variant. Do not use for production fracture jobs.
C TRANSFER_MODE=1 enables one-time H initialization from d2_transfer_table.inc.
C P2 diagnostics only: scientific expressions and shared-state behavior unchanged.
      SUBROUTINE UEL(RHS,AMATRX,SVARS,ENERGY,NDOFEL,NRHS,NSVARS,
     1     PROPS,NPROPS,COORDS,MCRD,NNODE,U,DU,V,A,JTYPE,TIME,DTIME,
     2     KSTEP,KINC,JELEM,PARAMS,NDLOAD,JDLTYP,ADLMAG,PREDEF,
     3     NPREDF,LFLAGS,MLVARX,DDLMAG,MDLOAD,PNEWDT,JPROPS,NJPROP,
     4     PERIOD)
      INCLUDE 'ABA_PARAM.INC'
      INTEGER N_ELEM,NSTV,TRANSFER_MODE
      PARAMETER (N_ELEM=8,NSTV=18,TRANSFER_MODE=1)
      DIMENSION RHS(MLVARX,*),AMATRX(NDOFEL,NDOFEL),
     1     SVARS(NSVARS),ENERGY(8),PROPS(NPROPS),COORDS(MCRD,NNODE),
     2     U(NDOFEL),DU(MLVARX,*),V(NDOFEL),A(NDOFEL),TIME(2),
     3     PARAMS(*),JDLTYP(MDLOAD,*),ADLMAG(MDLOAD,*),
     4     DDLMAG(MDLOAD,*),PREDEF(2,NPREDF,NNODE),LFLAGS(*),
     5     JPROPS(*)
      DOUBLE PRECISION USRVAR
      COMMON/KUSER/USRVAR(N_ELEM,NSTV,1)
      LOGICAL TRANSFER_DONE
      COMMON/D2INIT/TRANSFER_DONE(N_ELEM)
      SAVE /KUSER/,/D2INIT/
      INCLUDE 'd2_transfer_table.inc'
      INTEGER I,J,IDX
      DOUBLE PRECISION PHASE,HVAL
      CALL KP2TRACE(1,JELEM,0,KSTEP,KINC,'UEL_ENTER')
      IF (JELEM.EQ.1 .AND. KSTEP.EQ.1 .AND. KINC.EQ.1) THEN
        WRITE(7,*) 'P3SM0_UEL_OBSERVED'
      ENDIF

      DO I=1,NDOFEL
        DO J=1,NRHS
          RHS(I,J)=0.D0
        END DO
        DO J=1,NDOFEL
          AMATRX(I,J)=0.D0
        END DO
        AMATRX(I,I)=1.D0
      END DO

      IF (JELEM.LT.1 .OR. JELEM.GT.2*N_ELEM) THEN
        WRITE(7,*) 'D2 UEL invalid JELEM ',JELEM
        CALL XIT
      ENDIF

      IDX=0
      IF (JELEM.LE.N_ELEM) THEN
        DO I=1,D2_TRANSFER_COUNT
          IF (D2_TRANSFER_ELEM(I).EQ.JELEM) IDX=I
        END DO
      ELSE
        IDX=JELEM-N_ELEM
      ENDIF
      IF (IDX.LT.1 .OR. IDX.GT.D2_TRANSFER_COUNT) THEN
        WRITE(7,*) 'D2 missing transfer entry for JELEM ',JELEM
        CALL XIT
      ENDIF
      HVAL=D2_TRANSFER_H(IDX)

      IF (TRANSFER_MODE.EQ.1 .AND. KSTEP.EQ.1 .AND. KINC.EQ.1
     1    .AND. .NOT.TRANSFER_DONE(IDX)) THEN
        CALL KP3BEGINWRITE(2,1,IDX,JELEM,0,KSTEP,KINC,1)
        USRVAR(IDX,16,1)=HVAL
        CALL KP3ENDWRITE(2,IDX)
        CALL KP3BEGINWRITE(3,1,IDX,JELEM,0,KSTEP,KINC,1)
        USRVAR(IDX,18,1)=1.D0
        CALL KP3ENDWRITE(3,IDX)
        CALL KP3BEGINWRITE(4,1,IDX,JELEM,0,KSTEP,KINC,1)
        TRANSFER_DONE(IDX)=.TRUE.
        CALL KP3ENDWRITE(4,IDX)
      ENDIF

      IF (JTYPE.EQ.1) THEN
C       Phase layer: preserved Molnar deck declares U1 phase on Abaqus DOF 3.
C       Abaqus passes the active U1 element DOF values as U(1:4).
        PHASE=0.D0
        DO I=1,NNODE
          PHASE=PHASE+0.25D0*U(I)
        END DO
        IF (KSTEP.EQ.1 .AND. KINC.EQ.1) THEN
          CALL KP3BEGINWRITE(1,1,JELEM,JELEM,0,KSTEP,KINC,0)
          USRVAR(JELEM,15,1)=PHASE
          CALL KP3ENDWRITE(1,JELEM)
        ELSE
          CALL KP3READ(1,1,JELEM,JELEM,0,KSTEP,KINC,0)
          IF (PHASE.GT.USRVAR(JELEM,15,1)) THEN
            CALL KP3BEGINWRITE(1,1,JELEM,JELEM,0,KSTEP,KINC,0)
            USRVAR(JELEM,15,1)=PHASE
            CALL KP3ENDWRITE(1,JELEM)
          ENDIF
        ENDIF
        CALL KP3READ(1,1,JELEM,JELEM,0,KSTEP,KINC,0)
        CALL KP3READ(2,1,JELEM,JELEM,0,KSTEP,KINC,0)
        SVARS(1)=USRVAR(JELEM,15,1)
        SVARS(2)=USRVAR(JELEM,16,1)
      ELSEIF (JTYPE.EQ.2) THEN
C       Displacement layer is present only to preserve D2 routing topology.
        CALL KP3READ(1,1,IDX,JELEM,0,KSTEP,KINC,0)
        CALL KP3READ(2,1,IDX,JELEM,0,KSTEP,KINC,0)
        SVARS(1)=USRVAR(IDX,15,1)
        SVARS(2)=USRVAR(IDX,16,1)
      ELSE
        WRITE(7,*) 'D2 unsupported JTYPE ',JTYPE
        CALL XIT
      ENDIF
      RETURN
      END

      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,STRAN,DSTRAN,
     2 TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,NDI,NSHR,NTENS,
     3 NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,CELENT,
     4 DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,KSTEP,KINC)
      INCLUDE 'ABA_PARAM.INC'
      CHARACTER*80 CMNAME
      INTEGER N_ELEM,NSTV
      PARAMETER (N_ELEM=8,NSTV=18)
      DIMENSION STRESS(NTENS),STATEV(NSTATV),DDSDDE(NTENS,NTENS),
     1 DDSDDT(NTENS),DRPLDE(NTENS),STRAN(NTENS),DSTRAN(NTENS),
     2 TIME(2),PREDEF(*),DPRED(*),PROPS(NPROPS),COORDS(*),
     3 DROT(3,3),DFGRD0(3,3),DFGRD1(3,3)
      DOUBLE PRECISION USRVAR
      COMMON/KUSER/USRVAR(N_ELEM,NSTV,1)
      SAVE /KUSER/
      INTEGER I,J,PHYS
      DOUBLE PRECISION EMOD,ENU,EG,EG2,ELAM,PSI0,HOLD
      CALL KP2TRACE(2,NOEL,NPT,KSTEP,KINC,'UMAT_ENTER')
      IF (NOEL.EQ.17 .AND. NPT.EQ.1 .AND.
     1    KSTEP.EQ.1 .AND. KINC.EQ.1) THEN
        WRITE(7,*) 'P3SM0_UMAT_OBSERVED'
      ENDIF

      PHYS=NOEL-2*N_ELEM
      IF (PHYS.LT.1 .OR. PHYS.GT.N_ELEM) THEN
        WRITE(7,*) 'D2 UMAT invalid visualization element ',NOEL
        CALL XIT
      ENDIF
      DO I=1,NTENS
        STRESS(I)=0.D0
        DO J=1,NTENS
          DDSDDE(I,J)=0.D0
        END DO
      END DO
      EMOD=1.D-11
      ENU=0.3D0
      IF (NPROPS.GE.2) THEN
        EMOD=PROPS(1)
        ENU=PROPS(2)
      ENDIF
      EG=EMOD/(2.D0*(1.D0+ENU))
      EG2=2.D0*EG
      ELAM=EG2*ENU/(1.D0-2.D0*ENU)
      DO I=1,NDI
        DO J=1,NDI
          DDSDDE(I,J)=ELAM
        END DO
        DDSDDE(I,I)=EG2+ELAM
      END DO
      DO I=NDI+1,NTENS
        DDSDDE(I,I)=EG
      END DO
      DO I=1,NTENS
        DO J=1,NTENS
          STRESS(I)=STRESS(I)+DDSDDE(I,J)*DSTRAN(J)
        END DO
      END DO
      PSI0=0.D0
      DO I=1,NTENS
        HOLD=STRAN(I)+DSTRAN(I)
        PSI0=PSI0+0.5D0*HOLD*STRESS(I)
      END DO
      CALL KP3READ(2,2,PHYS,NOEL,NPT,KSTEP,KINC,0)
      IF (PSI0.GT.USRVAR(PHYS,16,1)) THEN
        CALL KP3BEGINWRITE(2,2,PHYS,NOEL,NPT,KSTEP,KINC,0)
        USRVAR(PHYS,16,1)=PSI0
        CALL KP3ENDWRITE(2,PHYS)
      ENDIF

      DO I=1,NSTATV
        STATEV(I)=0.D0
      END DO
      STATEV(1)=DBLE(PHYS)
      STATEV(2)=DBLE(NPT)
      CALL KP3READ(1,2,PHYS,NOEL,NPT,KSTEP,KINC,0)
      CALL KP3READ(2,2,PHYS,NOEL,NPT,KSTEP,KINC,0)
      STATEV(15)=USRVAR(PHYS,15,1)
      STATEV(16)=USRVAR(PHYS,16,1)
      RETURN
      END

      SUBROUTINE KP3READ(VAR_ID,ROUTINE_ID,IDX,ELEM,IP,KSTEP,KINC,
     1 INIT_FLAG)
      INCLUDE 'ABA_PARAM.INC'
      INTEGER VAR_ID,ROUTINE_ID,IDX,ELEM,IP,KSTEP,KINC,INIT_FLAG
      INTEGER ACCESS_SEEN,ACTIVE_RANK,ACTIVE_THREAD,CONFLICTS
      INTEGER LAST_RANK,LAST_THREAD
      INTEGER RANK,THREAD
      COMMON/KP3ACCESS/ACCESS_SEEN(4,2,8),
     1 ACTIVE_RANK(4,8),ACTIVE_THREAD(4,8),LAST_RANK(4,8),
     2 LAST_THREAD(4,8),CONFLICTS
      CALL GETRANK(RANK)
      THREAD=get_thread_id()
      CALL MUTEXLOCK(91)
      WRITE(7,*) 'P3T4_ACCESS ',VAR_ID,1,ROUTINE_ID,IDX,ELEM,IP,
     1  RANK,THREAD,KSTEP,KINC,INIT_FLAG
      IF (ACCESS_SEEN(VAR_ID,1,IDX).EQ.0) THEN
        ACCESS_SEEN(VAR_ID,1,IDX)=1
      ENDIF
      IF (ACTIVE_RANK(VAR_ID,IDX).NE.-1) THEN
        CONFLICTS=CONFLICTS+1
        WRITE(7,*) 'P3T4_CONFLICT_READ_DURING_WRITE ',VAR_ID,IDX,
     1    RANK,THREAD,ACTIVE_RANK(VAR_ID,IDX),
     2    ACTIVE_THREAD(VAR_ID,IDX)
      ENDIF
      CALL MUTEXUNLOCK(91)
      RETURN
      END

      SUBROUTINE KP3BEGINWRITE(VAR_ID,ROUTINE_ID,IDX,ELEM,IP,KSTEP,
     1 KINC,INIT_FLAG)
      INCLUDE 'ABA_PARAM.INC'
      INTEGER VAR_ID,ROUTINE_ID,IDX,ELEM,IP,KSTEP,KINC,INIT_FLAG
      INTEGER ACCESS_SEEN,ACTIVE_RANK,ACTIVE_THREAD,CONFLICTS
      INTEGER LAST_RANK,LAST_THREAD
      INTEGER RANK,THREAD
      COMMON/KP3ACCESS/ACCESS_SEEN(4,2,8),
     1 ACTIVE_RANK(4,8),ACTIVE_THREAD(4,8),LAST_RANK(4,8),
     2 LAST_THREAD(4,8),CONFLICTS
      CALL GETRANK(RANK)
      THREAD=get_thread_id()
      CALL MUTEXLOCK(91)
      WRITE(7,*) 'P3T4_BEGIN_WRITE ',VAR_ID,ROUTINE_ID,IDX,ELEM,IP,
     1  RANK,THREAD,KSTEP,KINC,INIT_FLAG
      WRITE(7,*) 'P3T4_ACCESS ',VAR_ID,2,ROUTINE_ID,IDX,ELEM,IP,
     1  RANK,THREAD,KSTEP,KINC,INIT_FLAG
      IF (ACCESS_SEEN(VAR_ID,2,IDX).EQ.0) THEN
        ACCESS_SEEN(VAR_ID,2,IDX)=1
      ELSEIF (INIT_FLAG.EQ.1) THEN
        WRITE(7,*) 'P3T4_DUPLICATE_INIT ',VAR_ID,IDX,RANK,THREAD,
     1    ELEM,IP,KSTEP,KINC
      ENDIF
      IF (ACTIVE_RANK(VAR_ID,IDX).NE.-1) THEN
        CONFLICTS=CONFLICTS+1
        WRITE(7,*) 'P3T4_CONFLICT_WRITE_DURING_WRITE ',VAR_ID,IDX,
     1    RANK,THREAD,ACTIVE_RANK(VAR_ID,IDX),
     2    ACTIVE_THREAD(VAR_ID,IDX)
      ENDIF
      IF (LAST_RANK(VAR_ID,IDX).NE.-1 .AND.
     1   (LAST_RANK(VAR_ID,IDX).NE.RANK .OR.
     2    LAST_THREAD(VAR_ID,IDX).NE.THREAD)) THEN
        WRITE(7,*) 'P3T4_OWNERSHIP_CHANGE ',VAR_ID,IDX,
     1    LAST_RANK(VAR_ID,IDX),LAST_THREAD(VAR_ID,IDX),RANK,THREAD
      ENDIF
      LAST_RANK(VAR_ID,IDX)=RANK
      LAST_THREAD(VAR_ID,IDX)=THREAD
      ACTIVE_RANK(VAR_ID,IDX)=RANK
      ACTIVE_THREAD(VAR_ID,IDX)=THREAD
      CALL MUTEXUNLOCK(91)
      RETURN
      END

      SUBROUTINE KP3ENDWRITE(VAR_ID,IDX)
      INCLUDE 'ABA_PARAM.INC'
      INTEGER VAR_ID,IDX
      INTEGER ACCESS_SEEN,ACTIVE_RANK,ACTIVE_THREAD,CONFLICTS
      INTEGER LAST_RANK,LAST_THREAD
      INTEGER RANK,THREAD
      COMMON/KP3ACCESS/ACCESS_SEEN(4,2,8),
     1 ACTIVE_RANK(4,8),ACTIVE_THREAD(4,8),LAST_RANK(4,8),
     2 LAST_THREAD(4,8),CONFLICTS
      CALL GETRANK(RANK)
      THREAD=get_thread_id()
      CALL MUTEXLOCK(91)
      WRITE(7,*) 'P3T4_END_WRITE ',VAR_ID,IDX,RANK,THREAD
      ACTIVE_RANK(VAR_ID,IDX)=-1
      ACTIVE_THREAD(VAR_ID,IDX)=-1
      CALL MUTEXUNLOCK(91)
      RETURN
      END

      SUBROUTINE UEXTERNALDB(LOP,LRESTART,TIME,DTIME,KSTEP,KINC)
      INCLUDE 'ABA_PARAM.INC'
      DIMENSION TIME(2)
      INTEGER RANK,THREAD
      INTEGER COUNTS
      COMMON/KP2DIAG/COUNTS(2,0:127,0:127)
      INTEGER ACCESS_SEEN,ACTIVE_RANK,ACTIVE_THREAD,CONFLICTS
      INTEGER LAST_RANK,LAST_THREAD
      COMMON/KP3ACCESS/ACCESS_SEEN(4,2,8),
     1 ACTIVE_RANK(4,8),ACTIVE_THREAD(4,8),LAST_RANK(4,8),
     2 LAST_THREAD(4,8),CONFLICTS
      IF (LOP.EQ.0) THEN
        CALL MUTEXINIT(91)
        WRITE(7,*) 'P3SM0_UEXTERNALDB_LOP0'
        WRITE(7,*) 'P3T4_INIT'
      ELSEIF (LOP.EQ.3) THEN
        RANK=0
        DO THREAD=0,127
          IF (COUNTS(1,RANK,THREAD).GT.0 .OR.
     1        COUNTS(2,RANK,THREAD).GT.0) THEN
            WRITE(7,*) 'P3T4_FINAL_THREAD_COUNTS ',
     1        RANK,THREAD,COUNTS(1,RANK,THREAD),
     2        COUNTS(2,RANK,THREAD)
          ENDIF
        END DO
        WRITE(7,*) 'P3T4_FINAL_CONFLICTS ',RANK,CONFLICTS
        WRITE(7,*) 'P3SM0_UEXTERNALDB_END'
      ENDIF
      RETURN
      END

      SUBROUTINE KP2TRACE(ROUTINE_ID,ELEM,IP,KSTEP,KINC,EVENT)
      INCLUDE 'ABA_PARAM.INC'
      INTEGER ROUTINE_ID,ELEM,IP,KSTEP,KINC,KPROCESSNUM,THREAD_ID
      INTEGER COUNTS
      CHARACTER*(*) EVENT
      COMMON/KP2DIAG/COUNTS(2,0:127,0:127)
      CALL GETRANK(KPROCESSNUM)
      THREAD_ID=get_thread_id()
      IF (KPROCESSNUM.LT.0 .OR. KPROCESSNUM.GT.127 .OR.
     1    THREAD_ID.LT.0 .OR. THREAD_ID.GT.127) THEN
        WRITE(7,*) 'P3T4_DIAG_ID_OUT_OF_RANGE ',KPROCESSNUM,
     1    THREAD_ID
        RETURN
      ENDIF
      CALL MUTEXLOCK(91)
      COUNTS(ROUTINE_ID,KPROCESSNUM,THREAD_ID)=
     1  COUNTS(ROUTINE_ID,KPROCESSNUM,THREAD_ID)+1
      IF (COUNTS(ROUTINE_ID,KPROCESSNUM,THREAD_ID).EQ.1) THEN
        WRITE(7,*) 'P3T4_FIRST_CALLBACK ',EVENT,KPROCESSNUM,
     1    THREAD_ID,
     2    ELEM,IP,KSTEP,KINC
      ENDIF
      CALL MUTEXUNLOCK(91)
      RETURN
      END

      BLOCK DATA D2BLOCK
      INTEGER N_ELEM,NSTV
      PARAMETER (N_ELEM=8,NSTV=18)
      DOUBLE PRECISION USRVAR
      COMMON/KUSER/USRVAR(N_ELEM,NSTV,1)
      LOGICAL TRANSFER_DONE
      COMMON/D2INIT/TRANSFER_DONE(N_ELEM)
      INTEGER COUNTS
      COMMON/KP2DIAG/COUNTS(2,0:127,0:127)
      INTEGER ACCESS_SEEN,ACTIVE_RANK,ACTIVE_THREAD,CONFLICTS
      INTEGER LAST_RANK,LAST_THREAD
      COMMON/KP3ACCESS/ACCESS_SEEN(4,2,8),
     1 ACTIVE_RANK(4,8),ACTIVE_THREAD(4,8),LAST_RANK(4,8),
     2 LAST_THREAD(4,8),CONFLICTS
      DATA USRVAR /144*0.D0/
      DATA TRANSFER_DONE /8*.FALSE./
      DATA COUNTS /32768*0/
      DATA ACCESS_SEEN /64*0/
      DATA ACTIVE_RANK /32*-1/
      DATA ACTIVE_THREAD /32*-1/
      DATA LAST_RANK /32*-1/
      DATA LAST_THREAD /32*-1/
      DATA CONFLICTS /0/
      END
