1

   Abaqus 2023                                  Date 30-Jul-2026   Time 13:55:22
   For use by TECHNISCHE UNIVERSITAET BERGAKADEMIE FREIBERG under license from Dassault Systemes or its subsidiary.

                                                                                 
                                                                                 
 STEP    1     INCREMENT     1     STEP TIME    0.00    


                        A N A L Y S I S    D A T A C H E C K




                        S T E P       1     S T A T I C   A N A L Y S I S


                                                                                          

          FIXED TIME INCREMENTS
          TIME INCREMENT IS                                    1.000E-03
          TIME PERIOD IS                                       0.500    

     LINEAR EQUATION SOLVER TYPE         DIRECT SPARSE

     COLLECTING MODEL CONSTRAINT INFORMATION FOR OVERCONSTRAINT CHECKS

     COLLECTING STEP CONSTRAINT INFORMATION FOR OVERCONSTRAINT CHECKS



     JOB TIME SUMMARY
       USER TIME (SEC)      =      1.4    
       SYSTEM TIME (SEC)    =     0.29    
       TOTAL CPU TIME (SEC) =      1.7    
       WALLCLOCK TIME (SEC) =            3
       MEMORY PEAK (GB)     =            0
