C D2 tiny transferred-state ingestion UEL/UMAT.
C Separate D2-only source variant. Do not use for production fracture jobs.
C TRANSFER_MODE=1 enables one-time H initialization from d2_transfer_table.inc.
      SUBROUTINE UEL(RHS,AMATRX,SVARS,ENERGY,NDOFEL,NRHS,NSVARS,
     1     PROPS,NPROPS,COORDS,MCRD,NNODE,U,DU,V,A,JTYPE,TIME,DTIME,
     2     KSTEP,KINC,JELEM,PARAMS,NDLOAD,JDLTYP,ADLMAG,PREDEF,
     3     NPREDF,LFLAGS,MLVARX,DDLMAG,MDLOAD,PNEWDT,JPROPS,NJPROP,
     4     PERIOD)
      INCLUDE 'ABA_PARAM.INC'
      INTEGER N_ELEM,NSTV,TRANSFER_MODE
      PARAMETER (N_ELEM=8,NSTV=18,TRANSFER_MODE=1)
      DIMENSION RHS(MLVARX,*),AMATRX(NDOFEL,NDOFEL),
     1     SVARS(NSVARS),ENERGY(8),PROPS(NPROPS),COORDS(MCRD,NNODE),
     2     U(NDOFEL),DU(MLVARX,*),V(NDOFEL),A(NDOFEL),TIME(2),
     3     PARAMS(*),JDLTYP(MDLOAD,*),ADLMAG(MDLOAD,*),
     4     DDLMAG(MDLOAD,*),PREDEF(2,NPREDF,NNODE),LFLAGS(*),
     5     JPROPS(*)
      DOUBLE PRECISION USRVAR
      COMMON/KUSER/USRVAR(N_ELEM,NSTV,1)
      LOGICAL TRANSFER_DONE
      COMMON/D2INIT/TRANSFER_DONE(N_ELEM)
      SAVE /KUSER/,/D2INIT/
      INCLUDE 'd2_transfer_table.inc'
      INTEGER I,J,IDX
      DOUBLE PRECISION PHASE,HVAL

      DO I=1,NDOFEL
        DO J=1,NRHS
          RHS(I,J)=0.D0
        END DO
        DO J=1,NDOFEL
          AMATRX(I,J)=0.D0
        END DO
        AMATRX(I,I)=1.D0
      END DO

      IF (JELEM.LT.1 .OR. JELEM.GT.2*N_ELEM) THEN
        WRITE(7,*) 'D2 UEL invalid JELEM ',JELEM
        CALL XIT
      ENDIF

      IDX=0
      IF (JELEM.LE.N_ELEM) THEN
        DO I=1,D2_TRANSFER_COUNT
          IF (D2_TRANSFER_ELEM(I).EQ.JELEM) IDX=I
        END DO
      ELSE
        IDX=JELEM-N_ELEM
      ENDIF
      IF (IDX.LT.1 .OR. IDX.GT.D2_TRANSFER_COUNT) THEN
        WRITE(7,*) 'D2 missing transfer entry for JELEM ',JELEM
        CALL XIT
      ENDIF
      HVAL=D2_TRANSFER_H(IDX)

      IF (TRANSFER_MODE.EQ.1 .AND. KSTEP.EQ.1 .AND. KINC.EQ.1
     1    .AND. .NOT.TRANSFER_DONE(IDX)) THEN
        USRVAR(IDX,16,1)=HVAL
        USRVAR(IDX,18,1)=1.D0
        TRANSFER_DONE(IDX)=.TRUE.
      ENDIF

      IF (JTYPE.EQ.1) THEN
C       Phase layer: preserved Molnar deck declares U1 phase on Abaqus DOF 3.
C       Abaqus passes the active U1 element DOF values as U(1:4).
        PHASE=0.D0
        DO I=1,NNODE
          PHASE=PHASE+0.25D0*U(I)
        END DO
        IF (KSTEP.EQ.1 .AND. KINC.EQ.1) THEN
          USRVAR(JELEM,15,1)=PHASE
        ELSE
          IF (PHASE.GT.USRVAR(JELEM,15,1)) THEN
            USRVAR(JELEM,15,1)=PHASE
          ENDIF
        ENDIF
        SVARS(1)=USRVAR(JELEM,15,1)
        SVARS(2)=USRVAR(JELEM,16,1)
      ELSEIF (JTYPE.EQ.2) THEN
C       Displacement layer is present only to preserve D2 routing topology.
        SVARS(1)=USRVAR(IDX,15,1)
        SVARS(2)=USRVAR(IDX,16,1)
      ELSE
        WRITE(7,*) 'D2 unsupported JTYPE ',JTYPE
        CALL XIT
      ENDIF
      RETURN
      END

      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,STRAN,DSTRAN,
     2 TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,NDI,NSHR,NTENS,
     3 NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,CELENT,
     4 DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,KSTEP,KINC)
      INCLUDE 'ABA_PARAM.INC'
      CHARACTER*80 CMNAME
      INTEGER N_ELEM,NSTV
      PARAMETER (N_ELEM=8,NSTV=18)
      DIMENSION STRESS(NTENS),STATEV(NSTATV),DDSDDE(NTENS,NTENS),
     1 DDSDDT(NTENS),DRPLDE(NTENS),STRAN(NTENS),DSTRAN(NTENS),
     2 TIME(2),PREDEF(*),DPRED(*),PROPS(NPROPS),COORDS(*),
     3 DROT(3,3),DFGRD0(3,3),DFGRD1(3,3)
      DOUBLE PRECISION USRVAR
      COMMON/KUSER/USRVAR(N_ELEM,NSTV,1)
      SAVE /KUSER/
      INTEGER I,J,PHYS
      DOUBLE PRECISION EMOD,ENU,EG,EG2,ELAM,PSI0,HOLD

      PHYS=NOEL-2*N_ELEM
      IF (PHYS.LT.1 .OR. PHYS.GT.N_ELEM) THEN
        WRITE(7,*) 'D2 UMAT invalid visualization element ',NOEL
        CALL XIT
      ENDIF
      DO I=1,NTENS
        STRESS(I)=0.D0
        DO J=1,NTENS
          DDSDDE(I,J)=0.D0
        END DO
      END DO
      EMOD=1.D-11
      ENU=0.3D0
      IF (NPROPS.GE.2) THEN
        EMOD=PROPS(1)
        ENU=PROPS(2)
      ENDIF
      EG=EMOD/(2.D0*(1.D0+ENU))
      EG2=2.D0*EG
      ELAM=EG2*ENU/(1.D0-2.D0*ENU)
      DO I=1,NDI
        DO J=1,NDI
          DDSDDE(I,J)=ELAM
        END DO
        DDSDDE(I,I)=EG2+ELAM
      END DO
      DO I=NDI+1,NTENS
        DDSDDE(I,I)=EG
      END DO
      DO I=1,NTENS
        DO J=1,NTENS
          STRESS(I)=STRESS(I)+DDSDDE(I,J)*DSTRAN(J)
        END DO
      END DO
      PSI0=0.D0
      DO I=1,NTENS
        HOLD=STRAN(I)+DSTRAN(I)
        PSI0=PSI0+0.5D0*HOLD*STRESS(I)
      END DO
      IF (PSI0.GT.USRVAR(PHYS,16,1)) THEN
        USRVAR(PHYS,16,1)=PSI0
      ENDIF

      DO I=1,NSTATV
        STATEV(I)=0.D0
      END DO
      STATEV(1)=DBLE(PHYS)
      STATEV(2)=DBLE(NPT)
      STATEV(15)=USRVAR(PHYS,15,1)
      STATEV(16)=USRVAR(PHYS,16,1)
      RETURN
      END

      BLOCK DATA D2BLOCK
      INTEGER N_ELEM,NSTV
      PARAMETER (N_ELEM=8,NSTV=18)
      DOUBLE PRECISION USRVAR
      COMMON/KUSER/USRVAR(N_ELEM,NSTV,1)
      LOGICAL TRANSFER_DONE
      COMMON/D2INIT/TRANSFER_DONE(N_ELEM)
      DATA USRVAR /144*0.D0/
      DATA TRANSFER_DONE /8*.FALSE./
      END
