C D3A3 full-target transferred-state ingestion UEL/UMAT.
C H table initializes once only from d3_transfer_table.inc during Step 1.
      SUBROUTINE UEL(RHS,AMATRX,SVARS,ENERGY,NDOFEL,NRHS,NSVARS,
     1     PROPS,NPROPS,COORDS,MCRD,NNODE,U,DU,V,A,JTYPE,TIME,DTIME,
     2     KSTEP,KINC,JELEM,PARAMS,NDLOAD,JDLTYP,ADLMAG,PREDEF,
     3     NPREDF,LFLAGS,MLVARX,DDLMAG,MDLOAD,PNEWDT,JPROPS,NJPROP,
     4     PERIOD)
      INCLUDE 'ABA_PARAM.INC'
      INTEGER N_ELEM,NSTV,NIP
      PARAMETER (N_ELEM=6400,NSTV=18,NIP=4)
      DIMENSION RHS(MLVARX,*),AMATRX(NDOFEL,NDOFEL),
     1     SVARS(NSVARS),ENERGY(8),PROPS(NPROPS),COORDS(MCRD,NNODE),
     2     U(NDOFEL),DU(MLVARX,*),V(NDOFEL),A(NDOFEL),TIME(2),
     3     PARAMS(*),JDLTYP(MDLOAD,*),ADLMAG(MDLOAD,*),
     4     DDLMAG(MDLOAD,*),PREDEF(2,NPREDF,NNODE),LFLAGS(*),
     5     JPROPS(*)
      DOUBLE PRECISION USRVAR
      COMMON/KUSER/USRVAR(N_ELEM,NSTV,NIP)
      LOGICAL TRANSFER_DONE
      COMMON/D3INIT/TRANSFER_DONE(N_ELEM,NIP)
      SAVE /KUSER/,/D3INIT/
      INCLUDE 'd3_transfer_table.inc'
      INTEGER I,J,IP,PHYS
      DOUBLE PRECISION PHASE,HVAL

      DO I=1,NDOFEL
        DO J=1,NRHS
          RHS(I,J)=0.D0
        END DO
        DO J=1,NDOFEL
          AMATRX(I,J)=0.D0
        END DO
        AMATRX(I,I)=1.D0
      END DO

      PHYS=JELEM
      IF (JELEM.GT.N_ELEM) PHYS=JELEM-N_ELEM
      IF (PHYS.LT.1 .OR. PHYS.GT.N_ELEM) THEN
        WRITE(7,*) 'D3A3 UEL invalid JELEM ',JELEM
        CALL XIT
      ENDIF

      DO IP=1,NIP
        HVAL=0.D0
        DO I=1,D3_TRANSFER_COUNT
          IF (D3_TRANSFER_ELEM(I).EQ.PHYS .AND.
     1        D3_TRANSFER_IP(I).EQ.IP) HVAL=D3_TRANSFER_H(I)
        END DO
        IF (KSTEP.EQ.1 .AND. KINC.EQ.1 .AND.
     1      .NOT.TRANSFER_DONE(PHYS,IP)) THEN
          USRVAR(PHYS,16,IP)=HVAL
          USRVAR(PHYS,18,IP)=1.D0
          TRANSFER_DONE(PHYS,IP)=.TRUE.
        ENDIF
      END DO

      IF (JTYPE.EQ.1) THEN
        PHASE=0.D0
        DO I=1,NNODE
          PHASE=PHASE+0.25D0*U(I)
        END DO
        DO IP=1,NIP
          IF (KSTEP.EQ.1 .AND. KINC.EQ.1) THEN
            USRVAR(PHYS,15,IP)=PHASE
          ELSEIF (PHASE.GT.USRVAR(PHYS,15,IP)) THEN
            USRVAR(PHYS,15,IP)=PHASE
          ENDIF
        END DO
      ENDIF
      DO I=1,NSVARS
        SVARS(I)=0.D0
      END DO
      SVARS(1)=USRVAR(PHYS,15,1)
      SVARS(2)=USRVAR(PHYS,16,1)
      RETURN
      END

      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,STRAN,DSTRAN,
     2 TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,NDI,NSHR,NTENS,
     3 NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,CELENT,
     4 DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,KSTEP,KINC)
      INCLUDE 'ABA_PARAM.INC'
      CHARACTER*80 CMNAME
      INTEGER N_ELEM,NSTV,NIP
      PARAMETER (N_ELEM=6400,NSTV=18,NIP=4)
      DIMENSION STRESS(NTENS),STATEV(NSTATV),DDSDDE(NTENS,NTENS),
     1 DDSDDT(NTENS),DRPLDE(NTENS),STRAN(NTENS),DSTRAN(NTENS),
     2 TIME(2),PREDEF(*),DPRED(*),PROPS(NPROPS),COORDS(*),
     3 DROT(3,3),DFGRD0(3,3),DFGRD1(3,3)
      DOUBLE PRECISION USRVAR
      COMMON/KUSER/USRVAR(N_ELEM,NSTV,NIP)
      SAVE /KUSER/
      INTEGER I,J,PHYS
      DOUBLE PRECISION EMOD,ENU,EG,EG2,ELAM,PSI0,HOLD

      PHYS=NOEL-2*N_ELEM
      IF (PHYS.LT.1 .OR. PHYS.GT.N_ELEM) THEN
        WRITE(7,*) 'D3A3 UMAT invalid visualization element ',NOEL
        CALL XIT
      ENDIF
      DO I=1,NTENS
        STRESS(I)=0.D0
        DO J=1,NTENS
          DDSDDE(I,J)=0.D0
        END DO
      END DO
      EMOD=1.D-11
      ENU=0.3D0
      IF (NPROPS.GE.2) THEN
        EMOD=PROPS(1)
        ENU=PROPS(2)
      ENDIF
      EG=EMOD/(2.D0*(1.D0+ENU))
      EG2=2.D0*EG
      ELAM=EG2*ENU/(1.D0-2.D0*ENU)
      DO I=1,NDI
        DO J=1,NDI
          DDSDDE(I,J)=ELAM
        END DO
        DDSDDE(I,I)=EG2+ELAM
      END DO
      DO I=NDI+1,NTENS
        DDSDDE(I,I)=EG
      END DO
      DO I=1,NTENS
        DO J=1,NTENS
          STRESS(I)=STRESS(I)+DDSDDE(I,J)*DSTRAN(J)
        END DO
      END DO
      PSI0=0.D0
      DO I=1,NTENS
        HOLD=STRAN(I)+DSTRAN(I)
        PSI0=PSI0+0.5D0*HOLD*STRESS(I)
      END DO
      IF (PSI0.GT.USRVAR(PHYS,16,NPT)) THEN
        USRVAR(PHYS,16,NPT)=PSI0
      ENDIF
      DO I=1,NSTATV
        STATEV(I)=0.D0
      END DO
      STATEV(1)=DBLE(PHYS)
      STATEV(2)=DBLE(NPT)
      STATEV(15)=USRVAR(PHYS,15,NPT)
      STATEV(16)=USRVAR(PHYS,16,NPT)
      RETURN
      END

      BLOCK DATA D3BLOCK
      INTEGER N_ELEM,NSTV,NIP
      PARAMETER (N_ELEM=6400,NSTV=18,NIP=4)
      DOUBLE PRECISION USRVAR
      COMMON/KUSER/USRVAR(N_ELEM,NSTV,NIP)
      LOGICAL TRANSFER_DONE
      COMMON/D3INIT/TRANSFER_DONE(N_ELEM,NIP)
      DATA USRVAR /460800*0.D0/
      DATA TRANSFER_DONE /25600*.FALSE./
      END
