#!/usr/bin/env python3
"""
Target Nonmatching Benchmark Mesh Generator:
Generates a deterministic 3-layer uncracked quad mesh (NM1) for the Mode-II domain
[-0.5, 0.5] x [-0.5, 0.5] mm, preserving exact physical geometry, material, and BCs
while providing a genuinely nonmatching discretization relative to PK10R1.
"""

from typing import Dict, List, Tuple, Any
from pathlib import Path


def generate_target_mesh_nm1(
    nx: int = 80,
    ny: int = 80,
    domain_x: Tuple[float, float] = (-0.5, 0.5),
    domain_y: Tuple[float, float] = (-0.5, 0.5)
) -> Dict[str, Any]:
    """
    Generates a structured 3-layer quad mesh (NM1) on the uncracked domain.
    Returns dictionary with:
      - nodes: Dict[node_id, (x, y)]
      - physical_elements: Dict[elem_id, (n1, n2, n3, n4)]
      - node_sets: Dict[name, List[node_id]]
      - element_sets: Dict[name, List[elem_id]]
      - num_nodes: int
      - num_elements: int
    """
    xmin, xmax = domain_x
    ymin, ymax = domain_y
    lx = xmax - xmin
    ly = ymax - ymin

    nodes: Dict[int, Tuple[float, float]] = {}
    node_grid: Dict[Tuple[int, int], int] = {}
    
    node_id = 1
    for j in range(ny + 1):
        y = ymin + (j / float(ny)) * ly
        for i in range(nx + 1):
            x = xmin + (i / float(nx)) * lx
            nodes[node_id] = (round(x, 10), round(y, 10))
            node_grid[(i, j)] = node_id
            node_id += 1

    # Generate physical quad elements
    physical_elements: Dict[int, Tuple[int, ...]] = {}
    elem_id = 1
    for j in range(ny):
        for i in range(nx):
            n1 = node_grid[(i, j)]
            n2 = node_grid[(i + 1, j)]
            n3 = node_grid[(i + 1, j + 1)]
            n4 = node_grid[(i, j + 1)]
            physical_elements[elem_id] = (n1, n2, n3, n4)
            elem_id += 1

    num_phys_elems = len(physical_elements)
    num_nodes = len(nodes)

    # Reference Point Node (RP)
    rp_node_id = num_nodes + 1
    nodes[rp_node_id] = (0.0, 0.5)

    # Node Sets
    bottom_nodes = []
    top_nodes = []
    for nid, (x, y) in nodes.items():
        if nid == rp_node_id:
            continue
        if abs(y - ymin) < 1e-7:
            bottom_nodes.append(nid)
        if abs(y - ymax) < 1e-7:
            top_nodes.append(nid)

    bottom_nodes.sort()
    top_nodes.sort()

    node_sets = {
        "ALL_NODES": sorted(list(nodes.keys())),
        "BOTTOM_NODES": bottom_nodes,
        "TOP_NODES": top_nodes,
        "RP_NODE": [rp_node_id]
    }

    # Element Sets for 3-layer architecture
    phase_quad_elems = list(range(1, num_phys_elems + 1))
    disp_quad_elems = list(range(num_phys_elems + 1, 2 * num_phys_elems + 1))
    vis_quad_elems = list(range(2 * num_phys_elems + 1, 3 * num_phys_elems + 1))

    element_sets = {
        "PHASE_QUAD": phase_quad_elems,
        "DISP_QUAD": disp_quad_elems,
        "VIS_QUAD": vis_quad_elems
    }

    return {
        "mesh_name": f"NM1_{nx}x{ny}",
        "nx": nx,
        "ny": ny,
        "domain_x": domain_x,
        "domain_y": domain_y,
        "nodes": nodes,
        "physical_elements": physical_elements,
        "node_sets": node_sets,
        "element_sets": element_sets,
        "num_nodes": len(nodes) - 1, # physical nodes excluding RP
        "num_physical_elements": num_phys_elems,
        "rp_node_id": rp_node_id
    }


def write_mesh_to_inp(
    mesh_data: Dict[str, Any],
    output_inp_path: str,
    title: str = "Mode-II Nonmatching Target Mesh NM1"
) -> str:
    """Writes target mesh definition (Nodes, Elements, Sets) to Abaqus INP format."""
    out_path = Path(output_inp_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    nodes = mesh_data["nodes"]
    phys_elems = mesh_data["physical_elements"]
    n_phys = mesh_data["num_physical_elements"]
    node_sets = mesh_data["node_sets"]
    rp_id = mesh_data["rp_node_id"]

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(f"*HEADING\n** {title}\n** Generated by Antigravity F195 state transfer tool\n")
        
        # 1. Nodal Coordinates
        f.write("*NODE\n")
        for nid in sorted(nodes.keys()):
            x, y = nodes[nid]
            f.write(f"{nid:8d}, {x:14.8f}, {y:14.8f}\n")

        # 2. Layer 1: Phase Quad Elements (U1)
        f.write("*USER ELEMENT, TYPE=U1, NODES=4, COORDINATES=2, PROPERTIES=6, VARIABLES=18, UNSYMM\n")
        f.write("3\n")
        f.write("*ELEMENT, TYPE=U1, ELSET=PHASE_QUAD\n")
        for eid, (n1, n2, n3, n4) in sorted(phys_elems.items()):
            f.write(f"{eid:8d}, {n1:8d}, {n2:8d}, {n3:8d}, {n4:8d}\n")

        # 3. Layer 2: Mech Quad Elements (U2)
        f.write("*USER ELEMENT, TYPE=U2, NODES=4, COORDINATES=2, PROPERTIES=6, VARIABLES=18, UNSYMM\n")
        f.write("1, 2\n")
        f.write("*ELEMENT, TYPE=U2, ELSET=DISP_QUAD\n")
        for eid, (n1, n2, n3, n4) in sorted(phys_elems.items()):
            mech_eid = eid + n_phys
            f.write(f"{mech_eid:8d}, {n1:8d}, {n2:8d}, {n3:8d}, {n4:8d}\n")

        # 4. Layer 3: Visualizer CPE4 Continuum Elements
        f.write("*ELEMENT, TYPE=CPE4, ELSET=VIS_QUAD\n")
        for eid, (n1, n2, n3, n4) in sorted(phys_elems.items()):
            vis_eid = eid + 2 * n_phys
            f.write(f"{vis_eid:8d}, {n1:8d}, {n2:8d}, {n3:8d}, {n4:8d}\n")

        # 5. Node Sets
        f.write("*NSET, NSET=BOTTOM_NODES\n")
        bn = node_sets["BOTTOM_NODES"]
        for i in range(0, len(bn), 10):
            chunk = bn[i:i+10]
            f.write(", ".join(f"{n:d}" for n in chunk) + "\n")

        f.write("*NSET, NSET=TOP_NODES\n")
        tn = node_sets["TOP_NODES"]
        for i in range(0, len(tn), 10):
            chunk = tn[i:i+10]
            f.write(", ".join(f"{n:d}" for n in chunk) + "\n")

        f.write(f"*NSET, NSET=RP_NODE\n{rp_id:d}\n")

    return str(out_path)
