# -*- coding: utf-8 -*-
"""Generate F43PRE3_GEOM.inp deck from Abaqus 2023 CAE database and audit model inventory."""

import os
import sys
import shutil
import json
import traceback

print("=== ABAQUS 2023 F43PRE3_GEOM DECK GENERATION & AUDIT STARTING ===")

source_cae = "/home/pr21vyci/projects/adaptive-remeshing-artifacts/f43pre3/ModeII_Geometry_Source_Abaqus2023.cae"
work_copy = "/tmp/ModeII_Geometry_WorkCopy_PRE3.cae"
output_inp_path = "/tmp/F43PRE3_GEOM.inp"

if not os.path.exists(source_cae):
    print("FATAL: Source CAE does not exist: " + source_cae)
    sys.exit(1)

shutil.copyfile(source_cae, work_copy)
print("Created temporary work copy at: " + work_copy)

open_fn = None
try:
    from abaqus import mdb, openMdb
    from abaqusConstants import *
    open_fn = openMdb
except ImportError:
    open_fn = globals().get('openMdb', getattr(sys.modules.get('__main__'), 'openMdb', None))

if open_fn is None:
    print("FATAL: openMdb function not found")
    sys.exit(1)

open_fn(pathName=work_copy)
print("Opened MDB successfully.")

if "ModeII_Geometry_Model" not in mdb.models:
    print("FATAL: ModeII_Geometry_Model not in mdb.models")
    sys.exit(1)

m = mdb.models["ModeII_Geometry_Model"]
print("Model: ModeII_Geometry_Model found")

# Audit inventory
parts = list(m.parts.keys())
instances = list(m.rootAssembly.instances.keys())
steps = list(m.steps.keys())
materials = list(m.materials.keys())
sections = list(m.sections.keys())
rules = list(m.remeshingRules.keys())

print("Parts: " + str(parts))
print("Instances: " + str(instances))
print("Steps: " + str(steps))
print("Materials: " + str(materials))
print("Sections: " + str(sections))
print("RemeshingRules: " + str(rules))

part_name = "PlatePart"
instance_name = "PlateInstance"
step_name = "Step-1"

assert part_name in parts, "PlatePart missing"
assert instance_name in instances, "PlateInstance missing"
assert step_name in steps, "Step-1 missing"
assert "Steel" in materials, "Steel material missing"
assert "SolidSection" in sections, "SolidSection missing"
assert "MISESERI_Adaptive_Rule" in rules, "MISESERI_Adaptive_Rule missing"

# Export INP deck
job_name = "F43PRE3_GEOM_TMP"
if job_name in mdb.jobs:
    del mdb.jobs[job_name]

j = mdb.Job(name=job_name, model="ModeII_Geometry_Model", type=ANALYSIS)
j.writeInput(consistencyChecking=OFF)
print("Input deck generated by Abaqus CAE.")

tmp_inp = job_name + ".inp"
if os.path.exists(tmp_inp):
    shutil.copyfile(tmp_inp, output_inp_path)
    print("Copied generated deck to: " + output_inp_path)
else:
    print("FATAL: Generated INP file not found: " + tmp_inp)
    sys.exit(1)

# Audit exported INP deck
cpe4_count = 0
cpe3_count = 0
total_elements = 0
node_count = 0
in_node = False
in_elem = False
curr_elem_type = None

with open(output_inp_path, "r") as f:
    lines = f.readlines()

for line in lines:
    l_strip = line.strip().upper()
    if l_strip.startswith("*NODE"):
        in_node = True
        in_elem = False
        continue
    elif l_strip.startswith("*ELEMENT"):
        in_node = False
        in_elem = True
        if "TYPE=CPE4" in l_strip:
            curr_elem_type = "CPE4"
        elif "TYPE=CPE3" in l_strip:
            curr_elem_type = "CPE3"
        else:
            curr_elem_type = "OTHER"
        continue
    elif l_strip.startswith("*") and not l_strip.startswith("**"):
        in_node = False
        in_elem = False
        curr_elem_type = None
        continue

    if in_node and l_strip and not l_strip.startswith("**"):
        parts_l = l_strip.split(",")
        if len(parts_l) >= 2 and parts_l[0].isdigit():
            node_count += 1

    if in_elem and l_strip and not l_strip.startswith("**"):
        parts_l = l_strip.split(",")
        if len(parts_l) >= 2 and parts_l[0].isdigit():
            total_elements += 1
            if curr_elem_type == "CPE4":
                cpe4_count += 1
            elif curr_elem_type == "CPE3":
                cpe3_count += 1

print("INP Audit Results:")
print("  Total Nodes: " + str(node_count))
print("  Total Elements: " + str(total_elements))
print("  CPE4 Elements: " + str(cpe4_count))
print("  CPE3 Elements: " + str(cpe3_count))

audit_summary = {
    "node_count": node_count,
    "total_elements": total_elements,
    "cpe4_count": cpe4_count,
    "cpe3_count": cpe3_count,
    "parts": parts,
    "instances": instances,
    "steps": steps,
    "materials": materials,
    "sections": sections,
    "remeshing_rules": rules
}

with open("/tmp/F43PRE3_GEOM_AUDIT.json", "w") as f:
    json.dump(audit_summary, f, indent=2)

print("AUDIT_COMPLETE_SUCCESS")
